In [27]:
import numpy as np
mat1=[[1,2],
        [3,4]]

mat2=[[0,5],
        [3,2]]  

mat1_shape = np.shape(mat1)
mat2_shape = np.shape(mat2)

mat1_np = np.array(mat1)
mat2_np = np.array(mat2)


result = np.zeros((mat1_shape[0]*mat2_shape[0], mat1_shape[1]*mat2_shape[1]))

for i in range(mat1_shape[0]):
    for j in range(mat1_shape[1]):
        result[i*mat2_shape[0]:(i+1)*mat2_shape[0], j*mat2_shape[1]:(j+1)*mat2_shape[1]] = mat1_np[i,j] * mat2_np

print("Resulting matrix:")
print(result)

Resulting matrix:
[[ 0.  5.  0. 10.]
 [ 3.  2.  6.  4.]
 [ 0. 15.  0. 20.]
 [ 9.  6. 12.  8.]]


In [31]:
import numpy as np
mat1=[[1,2],
        [3,4],
        [1,0]]

mat2=[[0,5,2],
        [6,7,3]]  

mat1_shape = np.shape(mat1)
mat2_shape = np.shape(mat2)

mat1_np = np.array(mat1)
mat2_np = np.array(mat2)


result = np.zeros((mat1_shape[0]*mat2_shape[0], mat1_shape[1]*mat2_shape[1]))

for i in range(mat1_shape[0]):
    for j in range(mat1_shape[1]):
        result[i*mat2_shape[0]:(i+1)*mat2_shape[0], j*mat2_shape[1]:(j+1)*mat2_shape[1]] = mat1_np[i,j] * mat2_np

print("Resulting matrix:")
print(result)

Resulting matrix:
[[ 0.  5.  2.  0. 10.  4.]
 [ 6.  7.  3. 12. 14.  6.]
 [ 0. 15.  6.  0. 20.  8.]
 [18. 21.  9. 24. 28. 12.]
 [ 0.  5.  2.  0.  0.  0.]
 [ 6.  7.  3.  0.  0.  0.]]


In [30]:


def is_magic_square(matrix):

    matrix = np.array(matrix)
    
    n = int(input("Enter the n: "))
    expected_sum = (n * (n**2 + 1)) // 2

    if matrix.shape != (n, n):
        return False
    
    
    # Check rows
    if not all(np.sum(matrix, axis=1) == expected_sum):
        return False
    
    # Check columns
    if not all(np.sum(matrix, axis=0) == expected_sum):
        return False
    
    # Check main diagonal
    if np.trace(matrix) != expected_sum:
        return False
    
    # Check secondary diagonal
    if np.sum(np.diag(np.fliplr(matrix))) != expected_sum:
        return False
    
    return True

sample_matrix = [[2,7,6],[9,5,1],[4,3,8]]
if is_magic_square(sample_matrix):
    print("Yes")
else:
    print("No")

No


In [42]:


import numpy as np
mat1=[[1,2],
        [3,4]]

mat2=[[0,5],
        [3,2]]  

mat1_shape = np.shape(mat1)
mat2_shape = np.shape(mat2)

mat1_np = np.array(mat1)
mat2_np = np.array(mat2)

# Matrix Multiplication
print("Matrix Multiplication:")
multiplication_result = np.dot(mat1_np, mat2_np)
print(multiplication_result)

# Matrix Addition
print("\nMatrix Addition:")
addition_result = mat1_np + mat2_np
print(addition_result)



Matrix Multiplication:
[[ 6  9]
 [12 23]]

Matrix Addition:
[[1 7]
 [6 6]]


In [44]:
import numpy as np

array = np.array([2000, 500, 100, 50, 10, 5, 2, 1])

rotations = int(input("Enter the number of rotations: "))

# Perform left rotation
left_rotated = np.roll(array, -rotations)

# Perform right rotation
right_rotated = np.roll(array, rotations)

print("\nOriginal array:", array)
print("Left rotated array:", left_rotated)
print("Right rotated array:", right_rotated)


Original array: [2000  500  100   50   10    5    2    1]
Left rotated array: [ 100   50   10    5    2    1 2000  500]
Right rotated array: [   2    1 2000  500  100   50   10    5]


In [58]:
import numpy as np
mat1=[[1,2],
        [3,4]]

mat2=[[0,5],
        [3,2]]  

mat1_shape = np.shape(mat1)
mat2_shape = np.shape(mat2)

mat1_np = np.array(mat1)
mat2_np = np.array(mat2)


result = np.zeros((mat1_shape[0]*mat2_shape[0], mat1_shape[1]*mat2_shape[1]))

for i in range(mat1_shape[0]):
    for j in range(mat1_shape[1]):
        result[i*mat2_shape[0]:(i+1)*mat2_shape[0], j*mat2_shape[1]:(j+1)*mat2_shape[1]] = mat1_np[i,j] * mat2_np

print("Resulting matrix:")
print(result)

Resulting matrix:
[[ 0.  5.  0. 10.]
 [ 3.  2.  6.  4.]
 [ 0. 15.  0. 20.]
 [ 9.  6. 12.  8.]]


In [61]:
import numpy as np
mat1=[[1,2],
        [3,4]]

mat2=[[0,5],
        [3,2]]  

mat1_shape = np.shape(mat1)
mat2_shape = np.shape(mat2)

mat1_np = np.array(mat1)
mat2_np = np.array(mat2)


result = np.zeros((mat1_shape[0]*mat2_shape[0], mat1_shape[1]*mat2_shape[1]))

for i in range(mat1_shape[0]):
    for j in range(mat1_shape[1]):
     print([i*mat2_shape[0]:(i+1)*mat2_shape[0]])

SyntaxError: invalid syntax (1094172068.py, line 19)

In [63]:
f"hi"

'hi'